### ISSUE TITLE
sourcegraph.com/sourcegraph/go-diff@v0.5.1: parsing go.mod: unexpected module path "github.com/sourcegraph/go-diff"

### ISSUE THREAD

**Issue by johnwyles** [sourcegraph/go-diff#35]
When running "go get -u" for github.com/johnwyles/vrddt-reboot:

```sourcegraph.com/sourcegraph/go-diff@v0.5.1: parsing go.mod: unexpected module path "github.com/sourcegraph/go-diff"```

**Comment by dmitshur** [comment]
Thanks for reporting. This is an issue that needs to be fixed in the github.com/johnwyles/vrddt-reboot project. It needs to start importing `go-diff` via its new import path `github.com/sourcegraph/go-diff/diff`. It has recently changed, see PR #30.

The old import path can only be used at v0.5.0 or older. `go get -u` tries to upgrade to the latest version, which is only valid at the new import path.

**Comment by johnwyles** [comment]
You are correct; I am new to go modules but basically I was able to clear this out by rm-ing the `go.mod` and starting fresh with a new `go mod init`. I am unsure which package was updated that this came from and how it became an issue but thank you for clearing that up. I will close this issue now :)

**Comment by ian-howell** [comment]
I'm still running into this issue when running `go get -u` on https://github.com/ian-howell/airshipctl. Refreshing the go.mod file doesn't seem to have helped. Further, `github.com/sourcegraph/go-diff` isn't even listed in my [go.mod](https://github.com/ian-howell/airshipctl/blob/master/go.mod) file. Any ideas?

**Comment by dmitshur** [comment]
@ian-howell It's not showing up in your go.mod file because you're requiring it indirectly, not directly.

Specifically, you're requiring the module `github.com/golangci/golangci-lint` at version v1.16.0, see [here](https://github.com/ian-howell/airshipctl/blob/35665072847d6f5befbfafd1fba18a6610e15560/go.mod#L11). That version requires `go-diff` at its previous path, see [here](https://github.com/golangci/golangci-lint/blob/v1.16.0/go.mod#L61). This has been fixed on `master` branch of `golangci-lint` via PR https://github.com/golangci/golangci-lint/pull/487.
